on:
  push:
  pull_request:

jobs:
  Run_tests:
    runs-on: ubuntu-latest

    env:
      # url should not need to chance as we are running qbittorrent locally on github servers.
      url: http://localhost
      port: 45378
      username: admin

      password: "@ByteArray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)"
      unencrypted_password: adminadmin

    steps:
      - name: Install qbittorrent-nox
        # Source: https://github.com/userdocs/qbittorrent-nox-static
        run: |
          mkdir -p ~/bin && source ~/.profile
          wget -qO ~/bin/qbittorrent-nox https://github.com/userdocs/qbittorrent-nox-static/releases/latest/download/x86_64-qbittorrent-nox
          chmod 700 ~/bin/qbittorrent-nox

      - name: Configure qBittorrent
        run: |
          mkdir -p ~/.config/qBittorrent
          cat > ~/.config/qBittorrent/qBittorrent.conf << 'EOF'
          [Preferences]
          WebUI\Password_PBKDF2="${{ env.password }}"
          WebUI\Port=${{ env.port }}
          WebUI\Username=${{ env.username }}
          EOF

      - name: Debug version
        run: ~/bin/qbittorrent-nox -v

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotenv
        run: |
          cat > .env << 'EOF'
          url = ${{ env.url }}
          port = ${{ env.port }}
          username = ${{ env.username }}
          password = ${{ env.unencrypted_password }}
          EOF

      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run tests
        run: |
          ~/bin/qbittorrent-nox &
          cargo test -- --include-ignored
